apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: findjob-ingress
  namespace: findjob
spec:
  rules:
  - host: findjob-applicant.cloudzcp.io
    http:
      paths:
      - path: /applicant
        backend:
          serviceName: findjob-applicant-service
          servicePort: 10001
