apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: findjob-recruit
  namespace: findjob
  labels:
    app: findjob-recruit
    component: findjob-recruit
spec:
  selector:
    matchLabels:
      app: findjob-recruit
      component: findjob-recruit
  replicas: 1
  minReadySeconds: 5
  progressDeadlineSeconds: 15
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: "100%"
  template:
    metadata:
      labels:
        app: findjob-recruit
        component: findjob-recruit
    spec:
      restartPolicy: Always
      containers:
      - name: findjob-recruit
        image: findjob/findjob-recruit-springboot
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - name: findjob-input
          containerPort: 10000
          protocol: TCP
      terminationGracePeriodSeconds: 160

