apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: findjob-ingress
  namespace: findjob
spec:
  rules:
  - host: findjob-company-company-company-company-company-company-company-company-company.cloudzcp.io
    http:
      paths:
      - path: /
        backend:
          serviceName: findjob-company-service
          servicePort: 9999
