apiVersion: v1
kind: Service
metadata:
  name: findjob-applicant-service
  namespace: findjob
  labels:
    app: findjob-applicant-service
spec:
  type: ClusterIP
  selector:
    app: findjob-applicant
  ports:
  - name: findjob-input
    port: 10001
    targetPort: findjob-input
    protocol: TCP
